version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: always
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql2/data

volumes:
  postgres_data:
    driver: local